version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/dat
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qUu-MAX-7eU-PSW
      POSTGRES_DB: audio_service_db
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d audio_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  back:
    container_name: back
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy