version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qUu-MAX-7eU-PSW
      POSTGRES_DB: audio_service_db
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  back:
    container_name: back
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - postgres