spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://postgres:5432/audio_service_db
    username: user
    password: qUu-MAX-7eU-PSW
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true