[package]
name = "music-streaming-app-deployment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
const_format = "0.2.32"
strum = { version = "0.25", features = ["derive"] }
